pluginManagement {
    repositories {
        maven { url = "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.fabricmc.net/" }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.fabricmc.net/" }
        mavenCentral()
    }
}

rootProject.name = "mc-auto-translation-tool"
include("translator-core")
include("platform-fabric-1.21.11")
include("platform-fabric-26.1")
include("platform-fabric-26.2")
