pluginManagement {
    repositories {
        maven { url = "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.minecraftforge.net/" }
        mavenCentral()
    }
}

rootProject.name = "mc-auto-translation-tool-forge-1.20.1"
